package tech.ada;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DeverealizarlogincorretamenteTest {
    private static WebDriver driver;
    private static Map<String, Object> vars;
    static JavascriptExecutor js;

    @BeforeAll
    public static void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterAll
    public static void tearDown() {
        driver.quit();
    }

    @Test
    public void deverealizarlogincorretamente() {
        // Test name: Deve realizar login corretamente
        // Step # | name | target | value
        // 1 | open | /login |
        driver.get("http://localhost:8080/login");
        // 2 | setWindowSize | 602x1009 |
        driver.manage().window().setSize(new Dimension(602, 1009));
        // 3 | click | id=username |
        WebElement username = driver.findElement(By.id("username"));

        username.click();
        // 4 | type | id=username | admin
        username.sendKeys("admin");
        // 5 | type | id=password | 123456
        driver.findElement(By.id("password")).sendKeys("123456");
        // 6 | click | css=.bg-red-600 |
        driver.findElement(By.cssSelector(".bg-red-600")).click();
        // 7 | click | css=.h-12 |
        driver.findElement(By.cssSelector(".h-12")).click();
        // 8 | assertElementPresent | linkText=@mcruzdev |
        {
            List<WebElement> elements = driver.findElements(By.linkText("@mcruzdev"));
            assert (elements.size() > 0);
        }
    }
}
