package tech.ada;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.List;
import java.util.UUID;

public class QuandooformulriodecadastroestivervlidodevecadastrarousuriocorretamenteTest {
    private static WebDriver driver;

    @BeforeAll
    public static void setUp() {
        driver = new ChromeDriver();
    }

    @AfterAll
    public static void tearDown() {
        driver.quit();
    }

    @Test
    public void quandooformulriodecadastroestivervlidodevecadastrarousuriocorretamente() {

        UUID uuid = UUID.randomUUID();
        System.out.println(uuid);
        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(1299, 1095));
        driver.findElement(By.cssSelector(".flex-1")).click();
        driver.findElement(By.cssSelector(".text-blue-300")).click();
        driver.findElement(By.id("firstName")).click();
        driver.findElement(By.id("firstName")).sendKeys("John");
        driver.findElement(By.id("lastName")).sendKeys("Doe");
        driver.findElement(By.id("email")).sendKeys("john.doe@email.com");
        driver.findElement(By.id("username")).sendKeys("johndoe" + uuid);
        driver.findElement(By.id("password")).sendKeys("johndoe@123");
        driver.findElement(By.id("register")).click();

        // buscar o elemento pelo atributo class = "text-white text-lg"
        // e verificar se o texto contido nele é "Registered with success!"


        // busca todos os elementos que tem as classes css text-white e text-lg

        long l = System.currentTimeMillis();

        String htmlTodo = driver.getPageSource();
        boolean existe = htmlTodo.contains("Registered with success!");
        Assertions.assertTrue(existe);

        long passado = System.currentTimeMillis() - l;
        System.out.println("Tempo de busca no page source: " + passado + " ms");

        // verifica se encontrou pelo menos um elemento
//      assert (elements.size() > 0);
//
//      // pega o primeiro elemento da lista
//      // [elemento1, elemento2, elemento3, ...]
//      // elemento1 o seu texto é "Registered with success!"???
//      // elemento2 o seu texto é "Registered with success!"???
//      // elemento3 o seu texto é "Registered with success!"???
//
//
//      // 0         , 1         , 2, ...
//      WebElement element = elements.get(0);
//
//      // verifica se o texto do elemento é igual a "Registered with success!"
//      assert (element.getText().equals("Registered with success!"));
    }


    @Test
    public void quandooformulriodecadastroestivervlidodevecadastrarousuriocorretamente_semPageSource() {

        UUID uuid = UUID.randomUUID();
        System.out.println(uuid);
        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(1299, 1095));
        driver.findElement(By.cssSelector(".flex-1")).click();
        driver.findElement(By.cssSelector(".text-blue-300")).click();
        driver.findElement(By.id("firstName")).click();
        driver.findElement(By.id("firstName")).sendKeys("John");
        driver.findElement(By.id("lastName")).sendKeys("Doe");
        driver.findElement(By.id("email")).sendKeys("john.doe@email.com");
        driver.findElement(By.id("username")).sendKeys("johndoe" + uuid);
        driver.findElement(By.id("password")).sendKeys("johndoe@123");
        driver.findElement(By.id("register")).click();

        // buscar o elemento pelo atributo class = "text-white text-lg"
        // e verificar se o texto contido nele é "Registered with success!"


        // busca todos os elementos que tem as classes css text-white e text-lg
        long l = System.currentTimeMillis();

        List<WebElement> elements = driver.findElements(By.cssSelector(".text-white.text-lg"));

        boolean encontrou = verificaSeOElementoTemOTexto(elements, "Registered with success!");

        Assertions.assertTrue(encontrou);
        long passado = System.currentTimeMillis() - l;
        System.out.println("Tempo de busca findelements " + passado + " ms");
        // verifica se encontrou pelo menos um elemento
//      assert (elements.size() > 0);
//
//      // pega o primeiro elemento da lista
//      // [elemento1, elemento2, elemento3, ..., elemento1000]
//      // elemento1 o seu texto é "Registered with success!"???
//      // elemento2 o seu texto é "Registered with success!"???
//      // elemento3 o seu texto é "Registered with success!"???
//
//
//      // 0         , 1         , 2, ...
//      WebElement element = elements.get(0);
//
//      // verifica se o texto do elemento é igual a "Registered with success!"
//      assert (element.getText().equals("Registered with success!"));
    }


    @Test
    void deveAparecerMensagemDeErroQuandoFirstNameForInvalid() {
        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(979, 1063));
        driver.findElement(By.cssSelector(".text-blue-300")).click();
        driver.findElement(By.id("firstName")).click();
        driver.findElement(By.id("firstName")).sendKeys("J");
        driver.findElement(By.id("register")).click();
        driver.findElement(By.cssSelector(".shadow-gray-700")).click();

        // buscar elementos que tenha o atributo class contendo text-rose-500, text-sm, w-full
        List<WebElement> elements = driver.findElements(By.cssSelector(".text-rose-500.text-sm.w-full"));

        boolean encontrou = verificaSeOElementoTemOTexto(elements, "First name must be at least 2 characters long");
        Assertions.assertTrue(encontrou);
    }

    @Test
    void deveAparecerMensagemDeErroQuandoLastNameForInvalido() {

        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(979, 1063));
        driver.findElement(By.cssSelector(".text-blue-300")).click();

        driver.findElement(By.id("firstName")).sendKeys("John");
        WebElement lastName = driver.findElement(By.id("lastName"));
        lastName.sendKeys("D");
        driver.findElement(By.id("register")).click();
        driver.findElement(By.cssSelector(".shadow-gray-700")).click();

        // buscar elementos que tenha o atributo class contendo text-rose-500, text-sm, w-full
        List<WebElement> elements = driver.findElements(By.cssSelector(".text-rose-500.text-sm.w-full"));

        boolean encontrou = verificaSeOElementoTemOTexto(elements, "Last name must be at least 2 characters long");

        Assertions.assertTrue(encontrou);
    }

    @Test
    void deveAparecerMensagemDeErroQuandoOEmailForInvalido() {

        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(979, 1063));
        driver.findElement(By.cssSelector(".text-blue-300")).click();
        driver.findElement(By.id("email")).sendKeys("john.doe");
        driver.findElement(By.id("register")).click();
        driver.findElement(By.cssSelector(".shadow-gray-700")).click();

        // buscar elementos que tenha o atributo class contendo text-rose-500, text-sm, w-full
        List<WebElement> elements = driver.findElements(By.cssSelector(".text-rose-500.text-sm.w-full"));

        boolean encontrou = verificaSeOElementoTemOTexto(elements, "Email should be valid");

        Assertions.assertTrue(encontrou);
    }

    @Test
    void deveAparecerMensagemDeErroQuandoUsernameForInvalido() {

        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(979, 1063));
        driver.findElement(By.cssSelector(".text-blue-300")).click();
        driver.findElement(By.id("username")).sendKeys("j");
        driver.findElement(By.id("register")).click();
        driver.findElement(By.cssSelector(".shadow-gray-700")).click();

        // buscar elementos que tenha o atributo class contendo text-rose-500, text-sm, w-full
        List<WebElement> elements = driver.findElements(By.cssSelector(".text-rose-500.text-sm.w-full"));

        boolean encontrou = verificaSeOElementoTemOTexto(elements, "Username must be at least 2 characters long");

        Assertions.assertTrue(encontrou);
    }

    @Test
    void deveAparecerMensagemDeErroQuandoOPasswordForInvalido() {

        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(979, 1063));
        driver.findElement(By.cssSelector(".text-blue-300")).click();
        driver.findElement(By.id("register")).click();
        driver.findElement(By.cssSelector(".shadow-gray-700")).click();

        // buscar elementos que tenha o atributo class contendo text-rose-500, text-sm, w-full
        List<WebElement> elements = driver.findElements(By.cssSelector(".text-rose-500.text-sm.w-full"));

        // flaky test
        boolean encontrou = verificaSeCadaTextoContemNoTextoDeUmElemento(elements,
                "Password must be at least 6 characters long", "must not be blank");

        Assertions.assertTrue(encontrou);
    }

    private static boolean verificaSeCadaTextoContemNoTextoDeUmElemento(List<WebElement> elements, String... textosQueDevemEstarContidos) {
        for (WebElement element : elements) {
            int length = textosQueDevemEstarContidos.length;
            int i = 0;
            String textoDoElemento = element.getText();
            for (String textoQueDeveEstarContido : textosQueDevemEstarContidos) {
                boolean contains = textoDoElemento.contains(textoQueDeveEstarContido);
                if (contains) {
                    i++;
                } else {
                    break;
                }
            }
            if (length == i) {
                return true;
            }
        }
        return false;
    }

    private static boolean verificaSeOElementoTemOTexto(List<WebElement> elements, String textoEsperado) {
        for (WebElement element : elements) {
            String textoDoElemento = element.getText();
            if (textoDoElemento.equals(textoEsperado)) {
                // encontrou o elemento com o texto esperado
                return true;
            }
        }
        return false;
    }
}
